# Generated by Django 4.2.8 on 2023-12-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_alter_noti_main_noti_platform_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="noti",
            name="is_error",
            field=models.BooleanField(
                default=False,
                help_text="알림 보내기 완료 여부를 저장하는 필드입니다.",
                verbose_name="알림 전송 여부",
            ),
        ),
    ]
