# Generated by Django 4.2.8 on 2023-12-13 08:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_noti_is_error"),
    ]

    operations = [
        migrations.RenameField(
            model_name="noti",
            old_name="is_error",
            new_name="is_send",
        ),
    ]
