# Generated by Django 4.2.8 on 2023-12-14 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0004_rename_is_error_noti_is_send"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="noti",
            options={"verbose_name": "알림", "verbose_name_plural": "알림"},
        ),
        migrations.CreateModel(
            name="NotiSendLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "result",
                    models.JSONField(
                        blank=True,
                        default=False,
                        help_text="메시징 모듈을 통해 전송 시도한 결과값을 저장하는 필드입니다.",
                        null=True,
                        verbose_name="메시징 모듈 호출 결과",
                    ),
                ),
                (
                    "noti",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notifications.noti",
                    ),
                ),
            ],
            options={
                "verbose_name": "알림 전송 이력",
                "verbose_name_plural": "알림 전송 이력",
            },
        ),
    ]
