# Generated by Django 4.2.8 on 2023-12-14 14:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0006_alter_notisendlog_result"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notiplatform",
            options={"verbose_name": "알림플랫폼", "verbose_name_plural": "알림플랫폼"},
        ),
    ]
