# Generated by Django 4.2.8 on 2023-12-14 11:35

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "사용자", "verbose_name_plural": "사용자"},
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="알림을 수신할 기본 휴대폰 번호입니다. 스크레이핑 모델마다 모두 다를 수 있습니다. 문자에서만 활용됩니다.",
                max_length=128,
                null=True,
                region=None,
                verbose_name="알림 수신 번호",
            ),
        ),
    ]
