version: "3.5"
services:
  selenium-hub:
    image: selenium/hub:4.16.1-20231212
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  chrome1:
    image: selenium/node-chrome:4.16.1-20231212
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - TZ=Asia/Seoul
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  chrome2:
    image: selenium/node-chrome:4.16.1-20231212
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - TZ=Asia/Seoul
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  chrome3:
    image: selenium/node-chrome:4.16.1-20231212
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - TZ=Asia/Seoul
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox1:
    image: selenium/node-firefox:4.16.1-20231212
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - TZ=Asia/Seoul
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox2:
    image: selenium/node-firefox:4.16.1-20231212
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - TZ=Asia/Seoul
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox3:
    image: selenium/node-firefox:4.16.1-20231212
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - TZ=Asia/Seoul
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
