# Generated by Django 4.2.8 on 2023-12-11 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_alter_noti_main_noti_platform_and_more"),
        ("scraping", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapingurl",
            name="main_noti_platform",
            field=models.ForeignKey(
                help_text="사용자가 어떤 알림을 메인으로 받을지 저장하는 필드입니다.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scraping_main_platform",
                to="notifications.notiplatform",
                verbose_name="메인 알림 플랫폼",
            ),
        ),
        migrations.AddField(
            model_name="scrapingurl",
            name="sub_noti_platform",
            field=models.ForeignKey(
                default=None,
                help_text="사용자가 어떤 알림을 서브로 받을지 저장하는 필드입니다.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scraping_sub_platform",
                to="notifications.notiplatform",
                verbose_name="서브 알림 플랫폼",
            ),
        ),
    ]
