# Generated by Django 4.2.8 on 2023-12-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraping", "0002_scrapingurl_main_noti_platform_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapingurl",
            name="is_activate",
            field=models.BooleanField(
                default=True,
                help_text="변동 알림을 계속 받을 것인지, 활성화 여부를 저장하는 값입니다.",
                verbose_name="활성화 여부",
            ),
        ),
    ]
