# Generated by Django 4.2.8 on 2023-12-13 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0004_rename_is_error_noti_is_send"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scraping", "0003_scrapingurl_is_activate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scrapingurl",
            name="last_scraping_log",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="scraping.scrapinglog",
            ),
        ),
        migrations.AlterField(
            model_name="scrapingurl",
            name="main_noti_platform",
            field=models.ForeignKey(
                blank=True,
                help_text="사용자가 어떤 알림을 메인으로 받을지 저장하는 필드입니다.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scraping_main_platform",
                to="notifications.notiplatform",
                verbose_name="메인 알림 플랫폼",
            ),
        ),
        migrations.AlterField(
            model_name="scrapingurl",
            name="scraping_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="scraping.scrapinggroup",
            ),
        ),
        migrations.AlterField(
            model_name="scrapingurl",
            name="sub_noti_platform",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="사용자가 어떤 알림을 서브로 받을지 저장하는 필드입니다.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scraping_sub_platform",
                to="notifications.notiplatform",
                verbose_name="서브 알림 플랫폼",
            ),
        ),
        migrations.AlterField(
            model_name="scrapingurl",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
