# Generated by Django 4.2.8 on 2023-12-14 11:35

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("scraping", "0004_alter_scrapingurl_last_scraping_log_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scrapinggroup",
            options={"verbose_name": "스크레이핑그룹", "verbose_name_plural": "스크레이핑그룹"},
        ),
        migrations.AlterModelOptions(
            name="scrapinglog",
            options={"verbose_name": "스크레이핑이력", "verbose_name_plural": "스크레이핑이력"},
        ),
        migrations.AlterModelOptions(
            name="scrapingurl",
            options={"verbose_name": "스크레이핑URL"},
        ),
        migrations.AddField(
            model_name="scrapingurl",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="알림을 수신할 휴대폰 번호입니다. 문자에서만 활용됩니다.",
                max_length=128,
                null=True,
                region=None,
                verbose_name="알림 수신 번호",
            ),
        ),
    ]
