# Generated by Django 4.2.8 on 2023-12-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraping", "0005_alter_scrapinggroup_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapingurl",
            name="website_favicon",
            field=models.CharField(
                blank=True,
                default="https://tenplestay.kro.kr/favicon.ico",
                help_text="제출한 url의 favicon의 경로를 저장한 field 입니다.",
                max_length=200,
                null=True,
                verbose_name="favicon url",
            ),
        ),
        migrations.AddField(
            model_name="scrapingurl",
            name="website_name",
            field=models.CharField(
                blank=True,
                help_text="제출한 url의 title만 뽑아내서 저장한 필드 입니다.",
                max_length=200,
                null=True,
                verbose_name="url 도메인",
            ),
        ),
    ]
